### ISSUE TITLE
Publish Failed with 1 Error and 6 Warnings

### ISSUE THREAD

**Issue by adelucia** [ligershark/publish-ignore#11]
I did an install of Version 1.0.7 and, when that didn't work, 1.0.6. No edits made to the publish ignore package files, and I received this error on Web Deploy:

The "ReadPublishIgnoreFile" task was not given a value for the required parameter "FilePath".

This task looks like this in the provided .target file:

<ReadPublishIgnoreFile FilePath="%(PubIgnoreFiles.Identity)">
    <Output TaskParameter="LinesFromFile" ItemName="_ls-PubIgnore-LinesRead"/>
</ReadPublishIgnoreFile>

Am I missing something? I am using Visual Studio Express 2013 for Web, Update 4. Please let me know if I can provide more useful information for you to address this issue. TY!

**Comment by adelucia** [comment]
<ReadPublishIgnoreFile FilePath="%(PubIgnoreFiles.Identity)">
      <Output TaskParameter="LinesFromFile" ItemName="_ls-PubIgnore-LinesRead"/>
    </ReadPublishIgnoreFile>

**Comment by sayedihashimi** [comment]
OK I've looked into it.

This can happen when there is no ```publish.ignore``` file. I've added a condition to the task and published as version ```1.0.8-beta``` to nuget.org. Please try it and let me know if you have any issues.

**Comment by adelucia** [comment]
Hello,

Thank you for the prompt reply. The error was very odd. I had a publish.ignore file, but I must have needed to restart Visual Studio because it wasn't working yesterday, and this morning it worked with no changes.

I need to be able to exclude unminified CSS and JS files, but include the minified versions for production, so I will work on support for the "!" feature this week. If you roll that out before I request a pull on my forked repo please let me know by replying here. Thanks again!!

**Comment by sayedihashimi** [comment]
>so I will work on support for the "!" feature this week. 

Sounds good. I look forward to the PR. Once we merge it I will release a new version to nuget.org.

I'll close this now.
